#ifndef OPCOMPANYSTRUCT_GLOBAL_H
#define OPCOMPANYSTRUCT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(OPCOMPANYSTRUCT_LIBRARY)
#  define OPCOMPANYSTRUCTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPCOMPANYSTRUCTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPCOMPANYSTRUCT_GLOBAL_H
