/* soapStub.h
   Generated by gSOAP 2.8.12 from EBMS_serverClass.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#include <vector>
#define SOAP_NAMESPACE_OF_ns1	"http://server.ebms"
#define SOAP_NAMESPACE_OF_ns1	"http://server.ebms"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20812
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE__ns1__login
#define SOAP_TYPE__ns1__login (8)
/* ns1:login */
class SOAP_CMAC _ns1__login
{
public:
	std::string *user;	/* optional element of type xsd:string */
	std::string *password;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 8; } /* = unique id SOAP_TYPE__ns1__login */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__login() { _ns1__login::soap_default(NULL); }
	virtual ~_ns1__login() { }
};
#endif

#ifndef SOAP_TYPE__ns1__loginResponse
#define SOAP_TYPE__ns1__loginResponse (9)
/* ns1:loginResponse */
class SOAP_CMAC _ns1__loginResponse
{
public:
	bool *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:boolean */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 9; } /* = unique id SOAP_TYPE__ns1__loginResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__loginResponse() { _ns1__loginResponse::soap_default(NULL); }
	virtual ~_ns1__loginResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__hasPrivilege
#define SOAP_TYPE__ns1__hasPrivilege (10)
/* ns1:hasPrivilege */
class SOAP_CMAC _ns1__hasPrivilege
{
public:
	std::string *user;	/* optional element of type xsd:string */
	std::string *password;	/* optional element of type xsd:string */
	std::string *level;	/* optional element of type xsd:string */
	std::string *oper;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 10; } /* = unique id SOAP_TYPE__ns1__hasPrivilege */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__hasPrivilege() { _ns1__hasPrivilege::soap_default(NULL); }
	virtual ~_ns1__hasPrivilege() { }
};
#endif

#ifndef SOAP_TYPE__ns1__hasPrivilegeResponse
#define SOAP_TYPE__ns1__hasPrivilegeResponse (11)
/* ns1:hasPrivilegeResponse */
class SOAP_CMAC _ns1__hasPrivilegeResponse
{
public:
	bool *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:boolean */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 11; } /* = unique id SOAP_TYPE__ns1__hasPrivilegeResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__hasPrivilegeResponse() { _ns1__hasPrivilegeResponse::soap_default(NULL); }
	virtual ~_ns1__hasPrivilegeResponse() { }
};
#endif

#ifndef SOAP_TYPE__ns1__doOperation
#define SOAP_TYPE__ns1__doOperation (12)
/* ns1:doOperation */
class SOAP_CMAC _ns1__doOperation
{
public:
	std::string *user;	/* optional element of type xsd:string */
	std::string *password;	/* optional element of type xsd:string */
	std::string *level;	/* optional element of type xsd:string */
	std::string *oper;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 12; } /* = unique id SOAP_TYPE__ns1__doOperation */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__doOperation() { _ns1__doOperation::soap_default(NULL); }
	virtual ~_ns1__doOperation() { }
};
#endif

#ifndef SOAP_TYPE__ns1__doOperationResponse
#define SOAP_TYPE__ns1__doOperationResponse (13)
/* ns1:doOperationResponse */
class SOAP_CMAC _ns1__doOperationResponse
{
public:
	std::string *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 13; } /* = unique id SOAP_TYPE__ns1__doOperationResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _ns1__doOperationResponse() { _ns1__doOperationResponse::soap_default(NULL); }
	virtual ~_ns1__doOperationResponse() { }
};
#endif

#ifndef SOAP_TYPE___ns1__doOperation
#define SOAP_TYPE___ns1__doOperation (22)
/* Operation wrapper: */
struct __ns1__doOperation
{
public:
	_ns1__doOperation *ns1__doOperation;	/* optional element of type ns1:doOperation */
public:
	int soap_type() const { return 22; } /* = unique id SOAP_TYPE___ns1__doOperation */
};
#endif

#ifndef SOAP_TYPE___ns1__login
#define SOAP_TYPE___ns1__login (26)
/* Operation wrapper: */
struct __ns1__login
{
public:
	_ns1__login *ns1__login;	/* optional element of type ns1:login */
public:
	int soap_type() const { return 26; } /* = unique id SOAP_TYPE___ns1__login */
};
#endif

#ifndef SOAP_TYPE___ns1__hasPrivilege
#define SOAP_TYPE___ns1__hasPrivilege (30)
/* Operation wrapper: */
struct __ns1__hasPrivilege
{
public:
	_ns1__hasPrivilege *ns1__hasPrivilege;	/* optional element of type ns1:hasPrivilege */
public:
	int soap_type() const { return 30; } /* = unique id SOAP_TYPE___ns1__hasPrivilege */
};
#endif

#ifndef SOAP_TYPE___ns1__doOperation_
#define SOAP_TYPE___ns1__doOperation_ (32)
/* Operation wrapper: */
struct __ns1__doOperation_
{
public:
	_ns1__doOperation *ns1__doOperation;	/* optional element of type ns1:doOperation */
public:
	int soap_type() const { return 32; } /* = unique id SOAP_TYPE___ns1__doOperation_ */
};
#endif

#ifndef SOAP_TYPE___ns1__login_
#define SOAP_TYPE___ns1__login_ (34)
/* Operation wrapper: */
struct __ns1__login_
{
public:
	_ns1__login *ns1__login;	/* optional element of type ns1:login */
public:
	int soap_type() const { return 34; } /* = unique id SOAP_TYPE___ns1__login_ */
};
#endif

#ifndef SOAP_TYPE___ns1__hasPrivilege_
#define SOAP_TYPE___ns1__hasPrivilege_ (36)
/* Operation wrapper: */
struct __ns1__hasPrivilege_
{
public:
	_ns1__hasPrivilege *ns1__hasPrivilege;	/* optional element of type ns1:hasPrivilege */
public:
	int soap_type() const { return 36; } /* = unique id SOAP_TYPE___ns1__hasPrivilege_ */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (37)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	int soap_type() const { return 37; } /* = unique id SOAP_TYPE_SOAP_ENV__Header */
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (38)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
public:
	int soap_type() const { return 38; } /* = unique id SOAP_TYPE_SOAP_ENV__Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (40)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
public:
	int soap_type() const { return 40; } /* = unique id SOAP_TYPE_SOAP_ENV__Detail */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (43)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
public:
	int soap_type() const { return 43; } /* = unique id SOAP_TYPE_SOAP_ENV__Reason */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (44)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
public:
	int soap_type() const { return 44; } /* = unique id SOAP_TYPE_SOAP_ENV__Fault */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __ns1__doOperation(struct soap*, _ns1__doOperation *ns1__doOperation, _ns1__doOperationResponse *ns1__doOperationResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__login(struct soap*, _ns1__login *ns1__login, _ns1__loginResponse *ns1__loginResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__hasPrivilege(struct soap*, _ns1__hasPrivilege *ns1__hasPrivilege, _ns1__hasPrivilegeResponse *ns1__hasPrivilegeResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__doOperation_(struct soap*, _ns1__doOperation *ns1__doOperation, _ns1__doOperationResponse *ns1__doOperationResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__login_(struct soap*, _ns1__login *ns1__login, _ns1__loginResponse *ns1__loginResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__hasPrivilege_(struct soap*, _ns1__hasPrivilege *ns1__hasPrivilege, _ns1__hasPrivilegeResponse *ns1__hasPrivilegeResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

extern "C" SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__doOperation(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__login(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__hasPrivilege(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__doOperation_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__login_(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__hasPrivilege_(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__doOperation(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__doOperation *ns1__doOperation, _ns1__doOperationResponse *ns1__doOperationResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__login(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__login *ns1__login, _ns1__loginResponse *ns1__loginResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hasPrivilege(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__hasPrivilege *ns1__hasPrivilege, _ns1__hasPrivilegeResponse *ns1__hasPrivilegeResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__doOperation_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__doOperation *ns1__doOperation, _ns1__doOperationResponse *ns1__doOperationResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__login_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__login *ns1__login, _ns1__loginResponse *ns1__loginResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hasPrivilege_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__hasPrivilege *ns1__hasPrivilege, _ns1__hasPrivilegeResponse *ns1__hasPrivilegeResponse);

#endif

/* End of soapStub.h */
