/* soapH.h
   Generated by gSOAP 2.8.12 from EBMS_serverClass.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);

#ifndef soap_write_bool
#define soap_write_bool(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_bool(soap, data, "boolean", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);

#ifndef soap_read_bool
#define soap_read_bool(soap, data) ( soap_begin_recv(soap) || !soap_get_bool(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_std__string(soap, data, "string", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);

inline std::string * soap_new_std__string(struct soap *soap, int n = -1) { return soap_instantiate_std__string(soap, n, NULL, NULL, NULL); }

inline std::string * soap_new_req_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); return _p; }

inline std::string * soap_new_set_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); return _p; }

inline void soap_delete_std__string(struct soap *soap, std::string *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__doOperationResponse
#define SOAP_TYPE__ns1__doOperationResponse (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__doOperationResponse(struct soap*, const char*, int, const _ns1__doOperationResponse *, const char*);
SOAP_FMAC3 _ns1__doOperationResponse * SOAP_FMAC4 soap_in__ns1__doOperationResponse(struct soap*, const char*, _ns1__doOperationResponse *, const char*);

#ifndef soap_write__ns1__doOperationResponse
#define soap_write__ns1__doOperationResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:doOperationResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__doOperationResponse * SOAP_FMAC4 soap_get__ns1__doOperationResponse(struct soap*, _ns1__doOperationResponse *, const char*, const char*);

#ifndef soap_read__ns1__doOperationResponse
#define soap_read__ns1__doOperationResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__doOperationResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__doOperationResponse * SOAP_FMAC2 soap_instantiate__ns1__doOperationResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__doOperationResponse * soap_new__ns1__doOperationResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__doOperationResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__doOperationResponse * soap_new_req__ns1__doOperationResponse(struct soap *soap) { _ns1__doOperationResponse *_p = soap_instantiate__ns1__doOperationResponse(soap, -1, NULL, NULL, NULL); return _p; }

inline _ns1__doOperationResponse * soap_new_set__ns1__doOperationResponse(struct soap *soap, std::string *return_) { _ns1__doOperationResponse *_p = soap_instantiate__ns1__doOperationResponse(soap, -1, NULL, NULL, NULL); _p->_ns1__doOperationResponse::return_ = return_; return _p; }

inline void soap_delete__ns1__doOperationResponse(struct soap *soap, _ns1__doOperationResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__doOperationResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__doOperation
#define SOAP_TYPE__ns1__doOperation (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__doOperation(struct soap*, const char*, int, const _ns1__doOperation *, const char*);
SOAP_FMAC3 _ns1__doOperation * SOAP_FMAC4 soap_in__ns1__doOperation(struct soap*, const char*, _ns1__doOperation *, const char*);

#ifndef soap_write__ns1__doOperation
#define soap_write__ns1__doOperation(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:doOperation", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__doOperation * SOAP_FMAC4 soap_get__ns1__doOperation(struct soap*, _ns1__doOperation *, const char*, const char*);

#ifndef soap_read__ns1__doOperation
#define soap_read__ns1__doOperation(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__doOperation(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__doOperation * SOAP_FMAC2 soap_instantiate__ns1__doOperation(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__doOperation * soap_new__ns1__doOperation(struct soap *soap, int n = -1) { return soap_instantiate__ns1__doOperation(soap, n, NULL, NULL, NULL); }

inline _ns1__doOperation * soap_new_req__ns1__doOperation(struct soap *soap) { _ns1__doOperation *_p = soap_instantiate__ns1__doOperation(soap, -1, NULL, NULL, NULL); return _p; }

inline _ns1__doOperation * soap_new_set__ns1__doOperation(struct soap *soap, std::string *user, std::string *password, std::string *level, std::string *oper) { _ns1__doOperation *_p = soap_instantiate__ns1__doOperation(soap, -1, NULL, NULL, NULL); _p->_ns1__doOperation::user = user; _p->_ns1__doOperation::password = password; _p->_ns1__doOperation::level = level; _p->_ns1__doOperation::oper = oper; return _p; }

inline void soap_delete__ns1__doOperation(struct soap *soap, _ns1__doOperation *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__doOperation(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__hasPrivilegeResponse
#define SOAP_TYPE__ns1__hasPrivilegeResponse (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__hasPrivilegeResponse(struct soap*, const char*, int, const _ns1__hasPrivilegeResponse *, const char*);
SOAP_FMAC3 _ns1__hasPrivilegeResponse * SOAP_FMAC4 soap_in__ns1__hasPrivilegeResponse(struct soap*, const char*, _ns1__hasPrivilegeResponse *, const char*);

#ifndef soap_write__ns1__hasPrivilegeResponse
#define soap_write__ns1__hasPrivilegeResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:hasPrivilegeResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__hasPrivilegeResponse * SOAP_FMAC4 soap_get__ns1__hasPrivilegeResponse(struct soap*, _ns1__hasPrivilegeResponse *, const char*, const char*);

#ifndef soap_read__ns1__hasPrivilegeResponse
#define soap_read__ns1__hasPrivilegeResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__hasPrivilegeResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__hasPrivilegeResponse * SOAP_FMAC2 soap_instantiate__ns1__hasPrivilegeResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__hasPrivilegeResponse * soap_new__ns1__hasPrivilegeResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__hasPrivilegeResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__hasPrivilegeResponse * soap_new_req__ns1__hasPrivilegeResponse(struct soap *soap) { _ns1__hasPrivilegeResponse *_p = soap_instantiate__ns1__hasPrivilegeResponse(soap, -1, NULL, NULL, NULL); return _p; }

inline _ns1__hasPrivilegeResponse * soap_new_set__ns1__hasPrivilegeResponse(struct soap *soap, bool *return_) { _ns1__hasPrivilegeResponse *_p = soap_instantiate__ns1__hasPrivilegeResponse(soap, -1, NULL, NULL, NULL); _p->_ns1__hasPrivilegeResponse::return_ = return_; return _p; }

inline void soap_delete__ns1__hasPrivilegeResponse(struct soap *soap, _ns1__hasPrivilegeResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__hasPrivilegeResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__hasPrivilege
#define SOAP_TYPE__ns1__hasPrivilege (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__hasPrivilege(struct soap*, const char*, int, const _ns1__hasPrivilege *, const char*);
SOAP_FMAC3 _ns1__hasPrivilege * SOAP_FMAC4 soap_in__ns1__hasPrivilege(struct soap*, const char*, _ns1__hasPrivilege *, const char*);

#ifndef soap_write__ns1__hasPrivilege
#define soap_write__ns1__hasPrivilege(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:hasPrivilege", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__hasPrivilege * SOAP_FMAC4 soap_get__ns1__hasPrivilege(struct soap*, _ns1__hasPrivilege *, const char*, const char*);

#ifndef soap_read__ns1__hasPrivilege
#define soap_read__ns1__hasPrivilege(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__hasPrivilege(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__hasPrivilege * SOAP_FMAC2 soap_instantiate__ns1__hasPrivilege(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__hasPrivilege * soap_new__ns1__hasPrivilege(struct soap *soap, int n = -1) { return soap_instantiate__ns1__hasPrivilege(soap, n, NULL, NULL, NULL); }

inline _ns1__hasPrivilege * soap_new_req__ns1__hasPrivilege(struct soap *soap) { _ns1__hasPrivilege *_p = soap_instantiate__ns1__hasPrivilege(soap, -1, NULL, NULL, NULL); return _p; }

inline _ns1__hasPrivilege * soap_new_set__ns1__hasPrivilege(struct soap *soap, std::string *user, std::string *password, std::string *level, std::string *oper) { _ns1__hasPrivilege *_p = soap_instantiate__ns1__hasPrivilege(soap, -1, NULL, NULL, NULL); _p->_ns1__hasPrivilege::user = user; _p->_ns1__hasPrivilege::password = password; _p->_ns1__hasPrivilege::level = level; _p->_ns1__hasPrivilege::oper = oper; return _p; }

inline void soap_delete__ns1__hasPrivilege(struct soap *soap, _ns1__hasPrivilege *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__hasPrivilege(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__loginResponse
#define SOAP_TYPE__ns1__loginResponse (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__loginResponse(struct soap*, const char*, int, const _ns1__loginResponse *, const char*);
SOAP_FMAC3 _ns1__loginResponse * SOAP_FMAC4 soap_in__ns1__loginResponse(struct soap*, const char*, _ns1__loginResponse *, const char*);

#ifndef soap_write__ns1__loginResponse
#define soap_write__ns1__loginResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:loginResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__loginResponse * SOAP_FMAC4 soap_get__ns1__loginResponse(struct soap*, _ns1__loginResponse *, const char*, const char*);

#ifndef soap_read__ns1__loginResponse
#define soap_read__ns1__loginResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__loginResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__loginResponse * SOAP_FMAC2 soap_instantiate__ns1__loginResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__loginResponse * soap_new__ns1__loginResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__loginResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__loginResponse * soap_new_req__ns1__loginResponse(struct soap *soap) { _ns1__loginResponse *_p = soap_instantiate__ns1__loginResponse(soap, -1, NULL, NULL, NULL); return _p; }

inline _ns1__loginResponse * soap_new_set__ns1__loginResponse(struct soap *soap, bool *return_) { _ns1__loginResponse *_p = soap_instantiate__ns1__loginResponse(soap, -1, NULL, NULL, NULL); _p->_ns1__loginResponse::return_ = return_; return _p; }

inline void soap_delete__ns1__loginResponse(struct soap *soap, _ns1__loginResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__loginResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__login
#define SOAP_TYPE__ns1__login (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__login(struct soap*, const char*, int, const _ns1__login *, const char*);
SOAP_FMAC3 _ns1__login * SOAP_FMAC4 soap_in__ns1__login(struct soap*, const char*, _ns1__login *, const char*);

#ifndef soap_write__ns1__login
#define soap_write__ns1__login(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || (data)->soap_put(soap, "ns1:login", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__login * SOAP_FMAC4 soap_get__ns1__login(struct soap*, _ns1__login *, const char*, const char*);

#ifndef soap_read__ns1__login
#define soap_read__ns1__login(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__login(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 _ns1__login * SOAP_FMAC2 soap_instantiate__ns1__login(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__login * soap_new__ns1__login(struct soap *soap, int n = -1) { return soap_instantiate__ns1__login(soap, n, NULL, NULL, NULL); }

inline _ns1__login * soap_new_req__ns1__login(struct soap *soap) { _ns1__login *_p = soap_instantiate__ns1__login(soap, -1, NULL, NULL, NULL); return _p; }

inline _ns1__login * soap_new_set__ns1__login(struct soap *soap, std::string *user, std::string *password) { _ns1__login *_p = soap_instantiate__ns1__login(soap, -1, NULL, NULL, NULL); _p->_ns1__login::user = user; _p->_ns1__login::password = password; return _p; }

inline void soap_delete__ns1__login(struct soap *soap, _ns1__login *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__login(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); _p->SOAP_ENV__Text = SOAP_ENV__Text; return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); _p->__type = __type; _p->fault = fault; return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); _p->__any = __any; _p->__type = __type; _p->fault = fault; return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__hasPrivilege_
#define SOAP_TYPE___ns1__hasPrivilege_ (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__hasPrivilege_(struct soap*, struct __ns1__hasPrivilege_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__hasPrivilege_(struct soap*, const struct __ns1__hasPrivilege_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__hasPrivilege_(struct soap*, const char*, int, const struct __ns1__hasPrivilege_ *, const char*);
SOAP_FMAC3 struct __ns1__hasPrivilege_ * SOAP_FMAC4 soap_in___ns1__hasPrivilege_(struct soap*, const char*, struct __ns1__hasPrivilege_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__hasPrivilege_(struct soap*, const struct __ns1__hasPrivilege_ *, const char*, const char*);

#ifndef soap_write___ns1__hasPrivilege_
#define soap_write___ns1__hasPrivilege_(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put___ns1__hasPrivilege_(soap, data, "-ns1:hasPrivilege", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct __ns1__hasPrivilege_ * SOAP_FMAC4 soap_get___ns1__hasPrivilege_(struct soap*, struct __ns1__hasPrivilege_ *, const char*, const char*);

#ifndef soap_read___ns1__hasPrivilege_
#define soap_read___ns1__hasPrivilege_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__hasPrivilege_(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct __ns1__hasPrivilege_ * SOAP_FMAC2 soap_instantiate___ns1__hasPrivilege_(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__hasPrivilege_ * soap_new___ns1__hasPrivilege_(struct soap *soap, int n = -1) { return soap_instantiate___ns1__hasPrivilege_(soap, n, NULL, NULL, NULL); }

inline struct __ns1__hasPrivilege_ * soap_new_req___ns1__hasPrivilege_(struct soap *soap) { struct __ns1__hasPrivilege_ *_p = soap_instantiate___ns1__hasPrivilege_(soap, -1, NULL, NULL, NULL); return _p; }

inline struct __ns1__hasPrivilege_ * soap_new_set___ns1__hasPrivilege_(struct soap *soap, _ns1__hasPrivilege *ns1__hasPrivilege) { struct __ns1__hasPrivilege_ *_p = soap_instantiate___ns1__hasPrivilege_(soap, -1, NULL, NULL, NULL); _p->ns1__hasPrivilege = ns1__hasPrivilege; return _p; }

inline void soap_delete___ns1__hasPrivilege_(struct soap *soap, struct __ns1__hasPrivilege_ *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__hasPrivilege_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__login_
#define SOAP_TYPE___ns1__login_ (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__login_(struct soap*, struct __ns1__login_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__login_(struct soap*, const struct __ns1__login_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__login_(struct soap*, const char*, int, const struct __ns1__login_ *, const char*);
SOAP_FMAC3 struct __ns1__login_ * SOAP_FMAC4 soap_in___ns1__login_(struct soap*, const char*, struct __ns1__login_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__login_(struct soap*, const struct __ns1__login_ *, const char*, const char*);

#ifndef soap_write___ns1__login_
#define soap_write___ns1__login_(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put___ns1__login_(soap, data, "-ns1:login", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct __ns1__login_ * SOAP_FMAC4 soap_get___ns1__login_(struct soap*, struct __ns1__login_ *, const char*, const char*);

#ifndef soap_read___ns1__login_
#define soap_read___ns1__login_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__login_(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct __ns1__login_ * SOAP_FMAC2 soap_instantiate___ns1__login_(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__login_ * soap_new___ns1__login_(struct soap *soap, int n = -1) { return soap_instantiate___ns1__login_(soap, n, NULL, NULL, NULL); }

inline struct __ns1__login_ * soap_new_req___ns1__login_(struct soap *soap) { struct __ns1__login_ *_p = soap_instantiate___ns1__login_(soap, -1, NULL, NULL, NULL); return _p; }

inline struct __ns1__login_ * soap_new_set___ns1__login_(struct soap *soap, _ns1__login *ns1__login) { struct __ns1__login_ *_p = soap_instantiate___ns1__login_(soap, -1, NULL, NULL, NULL); _p->ns1__login = ns1__login; return _p; }

inline void soap_delete___ns1__login_(struct soap *soap, struct __ns1__login_ *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__login_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__doOperation_
#define SOAP_TYPE___ns1__doOperation_ (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__doOperation_(struct soap*, struct __ns1__doOperation_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__doOperation_(struct soap*, const struct __ns1__doOperation_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__doOperation_(struct soap*, const char*, int, const struct __ns1__doOperation_ *, const char*);
SOAP_FMAC3 struct __ns1__doOperation_ * SOAP_FMAC4 soap_in___ns1__doOperation_(struct soap*, const char*, struct __ns1__doOperation_ *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__doOperation_(struct soap*, const struct __ns1__doOperation_ *, const char*, const char*);

#ifndef soap_write___ns1__doOperation_
#define soap_write___ns1__doOperation_(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put___ns1__doOperation_(soap, data, "-ns1:doOperation", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct __ns1__doOperation_ * SOAP_FMAC4 soap_get___ns1__doOperation_(struct soap*, struct __ns1__doOperation_ *, const char*, const char*);

#ifndef soap_read___ns1__doOperation_
#define soap_read___ns1__doOperation_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__doOperation_(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct __ns1__doOperation_ * SOAP_FMAC2 soap_instantiate___ns1__doOperation_(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__doOperation_ * soap_new___ns1__doOperation_(struct soap *soap, int n = -1) { return soap_instantiate___ns1__doOperation_(soap, n, NULL, NULL, NULL); }

inline struct __ns1__doOperation_ * soap_new_req___ns1__doOperation_(struct soap *soap) { struct __ns1__doOperation_ *_p = soap_instantiate___ns1__doOperation_(soap, -1, NULL, NULL, NULL); return _p; }

inline struct __ns1__doOperation_ * soap_new_set___ns1__doOperation_(struct soap *soap, _ns1__doOperation *ns1__doOperation) { struct __ns1__doOperation_ *_p = soap_instantiate___ns1__doOperation_(soap, -1, NULL, NULL, NULL); _p->ns1__doOperation = ns1__doOperation; return _p; }

inline void soap_delete___ns1__doOperation_(struct soap *soap, struct __ns1__doOperation_ *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__doOperation_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__hasPrivilege
#define SOAP_TYPE___ns1__hasPrivilege (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__hasPrivilege(struct soap*, struct __ns1__hasPrivilege *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__hasPrivilege(struct soap*, const struct __ns1__hasPrivilege *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__hasPrivilege(struct soap*, const char*, int, const struct __ns1__hasPrivilege *, const char*);
SOAP_FMAC3 struct __ns1__hasPrivilege * SOAP_FMAC4 soap_in___ns1__hasPrivilege(struct soap*, const char*, struct __ns1__hasPrivilege *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__hasPrivilege(struct soap*, const struct __ns1__hasPrivilege *, const char*, const char*);

#ifndef soap_write___ns1__hasPrivilege
#define soap_write___ns1__hasPrivilege(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put___ns1__hasPrivilege(soap, data, "-ns1:hasPrivilege", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct __ns1__hasPrivilege * SOAP_FMAC4 soap_get___ns1__hasPrivilege(struct soap*, struct __ns1__hasPrivilege *, const char*, const char*);

#ifndef soap_read___ns1__hasPrivilege
#define soap_read___ns1__hasPrivilege(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__hasPrivilege(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct __ns1__hasPrivilege * SOAP_FMAC2 soap_instantiate___ns1__hasPrivilege(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__hasPrivilege * soap_new___ns1__hasPrivilege(struct soap *soap, int n = -1) { return soap_instantiate___ns1__hasPrivilege(soap, n, NULL, NULL, NULL); }

inline struct __ns1__hasPrivilege * soap_new_req___ns1__hasPrivilege(struct soap *soap) { struct __ns1__hasPrivilege *_p = soap_instantiate___ns1__hasPrivilege(soap, -1, NULL, NULL, NULL); return _p; }

inline struct __ns1__hasPrivilege * soap_new_set___ns1__hasPrivilege(struct soap *soap, _ns1__hasPrivilege *ns1__hasPrivilege) { struct __ns1__hasPrivilege *_p = soap_instantiate___ns1__hasPrivilege(soap, -1, NULL, NULL, NULL); _p->ns1__hasPrivilege = ns1__hasPrivilege; return _p; }

inline void soap_delete___ns1__hasPrivilege(struct soap *soap, struct __ns1__hasPrivilege *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__hasPrivilege(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__login
#define SOAP_TYPE___ns1__login (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__login(struct soap*, struct __ns1__login *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__login(struct soap*, const struct __ns1__login *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__login(struct soap*, const char*, int, const struct __ns1__login *, const char*);
SOAP_FMAC3 struct __ns1__login * SOAP_FMAC4 soap_in___ns1__login(struct soap*, const char*, struct __ns1__login *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__login(struct soap*, const struct __ns1__login *, const char*, const char*);

#ifndef soap_write___ns1__login
#define soap_write___ns1__login(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put___ns1__login(soap, data, "-ns1:login", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct __ns1__login * SOAP_FMAC4 soap_get___ns1__login(struct soap*, struct __ns1__login *, const char*, const char*);

#ifndef soap_read___ns1__login
#define soap_read___ns1__login(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__login(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct __ns1__login * SOAP_FMAC2 soap_instantiate___ns1__login(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__login * soap_new___ns1__login(struct soap *soap, int n = -1) { return soap_instantiate___ns1__login(soap, n, NULL, NULL, NULL); }

inline struct __ns1__login * soap_new_req___ns1__login(struct soap *soap) { struct __ns1__login *_p = soap_instantiate___ns1__login(soap, -1, NULL, NULL, NULL); return _p; }

inline struct __ns1__login * soap_new_set___ns1__login(struct soap *soap, _ns1__login *ns1__login) { struct __ns1__login *_p = soap_instantiate___ns1__login(soap, -1, NULL, NULL, NULL); _p->ns1__login = ns1__login; return _p; }

inline void soap_delete___ns1__login(struct soap *soap, struct __ns1__login *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__login(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__doOperation
#define SOAP_TYPE___ns1__doOperation (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__doOperation(struct soap*, struct __ns1__doOperation *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__doOperation(struct soap*, const struct __ns1__doOperation *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__doOperation(struct soap*, const char*, int, const struct __ns1__doOperation *, const char*);
SOAP_FMAC3 struct __ns1__doOperation * SOAP_FMAC4 soap_in___ns1__doOperation(struct soap*, const char*, struct __ns1__doOperation *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__doOperation(struct soap*, const struct __ns1__doOperation *, const char*, const char*);

#ifndef soap_write___ns1__doOperation
#define soap_write___ns1__doOperation(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put___ns1__doOperation(soap, data, "-ns1:doOperation", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct __ns1__doOperation * SOAP_FMAC4 soap_get___ns1__doOperation(struct soap*, struct __ns1__doOperation *, const char*, const char*);

#ifndef soap_read___ns1__doOperation
#define soap_read___ns1__doOperation(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__doOperation(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC1 struct __ns1__doOperation * SOAP_FMAC2 soap_instantiate___ns1__doOperation(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__doOperation * soap_new___ns1__doOperation(struct soap *soap, int n = -1) { return soap_instantiate___ns1__doOperation(soap, n, NULL, NULL, NULL); }

inline struct __ns1__doOperation * soap_new_req___ns1__doOperation(struct soap *soap) { struct __ns1__doOperation *_p = soap_instantiate___ns1__doOperation(soap, -1, NULL, NULL, NULL); return _p; }

inline struct __ns1__doOperation * soap_new_set___ns1__doOperation(struct soap *soap, _ns1__doOperation *ns1__doOperation) { struct __ns1__doOperation *_p = soap_instantiate___ns1__doOperation(soap, -1, NULL, NULL, NULL); _p->ns1__doOperation = ns1__doOperation; return _p; }

inline void soap_delete___ns1__doOperation(struct soap *soap, struct __ns1__doOperation *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__doOperation(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#endif

#ifndef SOAP_TYPE_PointerTo_ns1__hasPrivilegeResponse
#define SOAP_TYPE_PointerTo_ns1__hasPrivilegeResponse (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__hasPrivilegeResponse(struct soap*, _ns1__hasPrivilegeResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__hasPrivilegeResponse(struct soap*, const char *, int, _ns1__hasPrivilegeResponse *const*, const char *);
SOAP_FMAC3 _ns1__hasPrivilegeResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__hasPrivilegeResponse(struct soap*, const char*, _ns1__hasPrivilegeResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__hasPrivilegeResponse(struct soap*, _ns1__hasPrivilegeResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__hasPrivilegeResponse
#define soap_write_PointerTo_ns1__hasPrivilegeResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__hasPrivilegeResponse(soap, data, "ns1:hasPrivilegeResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__hasPrivilegeResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__hasPrivilegeResponse(struct soap*, _ns1__hasPrivilegeResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__hasPrivilegeResponse
#define soap_read_PointerTo_ns1__hasPrivilegeResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__hasPrivilegeResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__hasPrivilege
#define SOAP_TYPE_PointerTo_ns1__hasPrivilege (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__hasPrivilege(struct soap*, _ns1__hasPrivilege *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__hasPrivilege(struct soap*, const char *, int, _ns1__hasPrivilege *const*, const char *);
SOAP_FMAC3 _ns1__hasPrivilege ** SOAP_FMAC4 soap_in_PointerTo_ns1__hasPrivilege(struct soap*, const char*, _ns1__hasPrivilege **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__hasPrivilege(struct soap*, _ns1__hasPrivilege *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__hasPrivilege
#define soap_write_PointerTo_ns1__hasPrivilege(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__hasPrivilege(soap, data, "ns1:hasPrivilege", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__hasPrivilege ** SOAP_FMAC4 soap_get_PointerTo_ns1__hasPrivilege(struct soap*, _ns1__hasPrivilege **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__hasPrivilege
#define soap_read_PointerTo_ns1__hasPrivilege(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__hasPrivilege(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__loginResponse
#define SOAP_TYPE_PointerTo_ns1__loginResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__loginResponse(struct soap*, _ns1__loginResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__loginResponse(struct soap*, const char *, int, _ns1__loginResponse *const*, const char *);
SOAP_FMAC3 _ns1__loginResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__loginResponse(struct soap*, const char*, _ns1__loginResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__loginResponse(struct soap*, _ns1__loginResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__loginResponse
#define soap_write_PointerTo_ns1__loginResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__loginResponse(soap, data, "ns1:loginResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__loginResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__loginResponse(struct soap*, _ns1__loginResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__loginResponse
#define soap_read_PointerTo_ns1__loginResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__loginResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__login
#define SOAP_TYPE_PointerTo_ns1__login (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__login(struct soap*, _ns1__login *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__login(struct soap*, const char *, int, _ns1__login *const*, const char *);
SOAP_FMAC3 _ns1__login ** SOAP_FMAC4 soap_in_PointerTo_ns1__login(struct soap*, const char*, _ns1__login **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__login(struct soap*, _ns1__login *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__login
#define soap_write_PointerTo_ns1__login(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__login(soap, data, "ns1:login", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__login ** SOAP_FMAC4 soap_get_PointerTo_ns1__login(struct soap*, _ns1__login **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__login
#define soap_read_PointerTo_ns1__login(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__login(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__doOperationResponse
#define SOAP_TYPE_PointerTo_ns1__doOperationResponse (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__doOperationResponse(struct soap*, _ns1__doOperationResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__doOperationResponse(struct soap*, const char *, int, _ns1__doOperationResponse *const*, const char *);
SOAP_FMAC3 _ns1__doOperationResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__doOperationResponse(struct soap*, const char*, _ns1__doOperationResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__doOperationResponse(struct soap*, _ns1__doOperationResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__doOperationResponse
#define soap_write_PointerTo_ns1__doOperationResponse(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__doOperationResponse(soap, data, "ns1:doOperationResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__doOperationResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__doOperationResponse(struct soap*, _ns1__doOperationResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__doOperationResponse
#define soap_read_PointerTo_ns1__doOperationResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__doOperationResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__doOperation
#define SOAP_TYPE_PointerTo_ns1__doOperation (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__doOperation(struct soap*, _ns1__doOperation *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__doOperation(struct soap*, const char *, int, _ns1__doOperation *const*, const char *);
SOAP_FMAC3 _ns1__doOperation ** SOAP_FMAC4 soap_in_PointerTo_ns1__doOperation(struct soap*, const char*, _ns1__doOperation **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__doOperation(struct soap*, _ns1__doOperation *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__doOperation
#define soap_write_PointerTo_ns1__doOperation(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTo_ns1__doOperation(soap, data, "ns1:doOperation", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 _ns1__doOperation ** SOAP_FMAC4 soap_get_PointerTo_ns1__doOperation(struct soap*, _ns1__doOperation **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__doOperation
#define soap_read_PointerTo_ns1__doOperation(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__doOperation(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTobool
#define SOAP_TYPE_PointerTobool (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTobool(struct soap*, bool *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTobool(struct soap*, const char *, int, bool *const*, const char *);
SOAP_FMAC3 bool ** SOAP_FMAC4 soap_in_PointerTobool(struct soap*, const char*, bool **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTobool(struct soap*, bool *const*, const char*, const char*);

#ifndef soap_write_PointerTobool
#define soap_write_PointerTobool(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTobool(soap, data, "boolean", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 bool ** SOAP_FMAC4 soap_get_PointerTobool(struct soap*, bool **, const char*, const char*);

#ifndef soap_read_PointerTobool
#define soap_read_PointerTobool(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTobool(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);

#ifndef soap_write_PointerTostd__string
#define soap_write_PointerTostd__string(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_PointerTostd__string(soap, data, "string", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);

#ifndef soap_read_PointerTostd__string
#define soap_read_PointerTostd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostd__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_set_omode(soap, SOAP_XML_TREE), soap_begin(soap), soap_begin_send(soap) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#endif

/* End of soapH.h */
